Documentation
vasu31dev/playwright-ts-template pull request #1
Opened 2023-09-27 12:19 UTC by vidyavemulapalli

update to 'type' action to 'pressSequentially' as per new Playwright/test 1.38

2023-09-27 12:50 UTC, vasu31dev requested changes
Please update the document as per the review comments

2023-09-27 12:50 UTC, vasu31dev commented on docs/Utilities.md
> +3. `pressSequentially(input: string | Locator, value: string, options?: FillOptions)`: This function fills a form field with a specific value. The input parameter is a string or Locator representing
@vidyavemulapalli fill is replaced with pressSequentially. Needs correction. Also Can you please add the below points too for fill?
- Clears input
- single input event

2023-09-27 12:50 UTC, vasu31dev commented on docs/Utilities.md
> +4. `pressSequentially(input: string | Locator, value: string, options?: TypeOptions)`: This function enters text into a field character by character, as if it was a user with a real keyboard. The inp
@vidyavemulapalli Can you please add the below points too for pressSequentially?
- Does not Clears input
- sends a keydown, keypress/input, and keyup event for each character in the text

2023-09-27 13:54 UTC, vidyavemulapalli commented on docs/Utilities.md
> +4. `pressSequentially(input: string | Locator, value: string, options?: TypeOptions)`: This function enters text into a field character by character, as if it was a user with a real keyboard. The inp
@vasu31dev  Addressed the feedback comments in the latest commit

2023-09-28 11:38 UTC, vasu31dev approved these changes
Thanks for adding the feedback. looks good now!

2023-09-28 11:38 UTC, merged