Moved to common step to beforeEach scope within the test.describe group and url update to POM comparision image
vasu31dev/playwright-ts-template pull request #17
Opened 2024-01-16 18:18 UTC by vidyavemulapalli

…

2024-01-16 18:19 UTC, vidyavemulapalli commented on docs/POMComparision.md
> +![Traditional vs. Preferred POM Spec file](https://raw.githubusercontent.com/vasu31dev/playwright-ts-template/main/docs/images/SpecFile-Comparision.png)
I need to test this url once it gets merged. I am unable to verify it from Readme preview

2024-01-17 10:08 UTC, vidyavemulapalli commented on README.md
> +// eslint-disable-next-line playwright/require-top-level-describe
@vasu31dev I have to disable this eslint check in order to add beforeEach hook at spec file level

2024-01-17 10:10 UTC, vidyavemulapalli commented on tests/specs/sauce-demo-all-pass.spec.ts
> +// eslint-disable-next-line playwright/require-top-level-describe
@vasu31dev i have to disable this eslint check for this line in order to add beforeEach hook at spec file level

2024-01-17 13:19 UTC, vasu31dev requested changes

2024-01-17 13:19 UTC, vasu31dev commented on tests/specs/sauce-demo-all-pass.spec.ts
> +
Add test. beforeEach inside the test .describe

2024-01-17 14:31 UTC, vidyavemulapalli commented on tests/specs/sauce-demo-all-pass.spec.ts
> +
Deleted the beforeEach hook in scope with spec file and added it with in the scope of test.describe block

2024-01-17 14:45 UTC, vasu31dev approved these changes

2024-01-17 14:47 UTC, merged