README.md doc main page updates with better rephrases
vasu31dev/playwright-ts-template pull request #2
Opened 2023-09-28 16:15 UTC by vidyavemulapalli

2023-09-28 16:59 UTC, vasu31dev requested changes

2023-09-28 16:59 UTC, vasu31dev commented on README.md
> +- **Utility Functions**: Simplifies the task of identifying elements and performing routine actions and verifications, such as clicking buttons, inputting data into forms, and verifying elements. Add
@vidyavemulapalli The old one looks simple. Can you rephrase this?

2023-09-29 09:18 UTC, vidyavemulapalli commented on README.md
> +- **Utility Functions**: Simplifies the task of identifying elements and performing routine actions and verifications, such as clicking buttons, inputting data into forms, and verifying elements. Add
@vasu31dev Updated as per review comment in the commit https://github.com/vasu31dev/playwright-ts-template/pull/2/commits/e6fea251ec5dfb3dbc9aff12699cc9a9e9ff2406

Please review. Thanks

2023-09-29 12:07 UTC, vasu31dev approved these changes
Approved. Thank you

2023-09-29 12:07 UTC, merged