added documentation for soft assertions
vasu31dev/playwright-ts-template pull request #22
Opened 2024-01-23 18:08 UTC by vidyavemulapalli

2024-01-23 23:54 UTC, vasu31dev requested changes

2024-01-23 23:54 UTC, vasu31dev commented on README.md
> -- **Soft Assertions for Non-Critical Checks**: Use a soft assertion when a test assertion isn't critical, allowing the test to continue and fail at the end. For critical assertions, use a hard assert
You can add this link inside the *Soft Assertions content as reference.  [Playwright Soft Assertions documentation](https://playwright.dev/docs/test-assertions#soft-assertions)

2024-01-23 23:54 UTC, vasu31dev commented on docs/Utilities.md
> +// use this in the spec file to stop the test if there are failures for any soft assertions
Rename this to - Use this in the spec file to stop and fail the test at this step if there are failures for any soft assertions till now instead of failing at the end of the test

2024-01-24 09:53 UTC, vidyavemulapalli commented on docs/Utilities.md
> +// use this in the spec file to stop the test if there are failures for any soft assertions
Review comments addressed

2024-01-24 09:53 UTC, vidyavemulapalli commented on README.md
> -- **Soft Assertions for Non-Critical Checks**: Use a soft assertion when a test assertion isn't critical, allowing the test to continue and fail at the end. For critical assertions, use a hard assert
Review comments addressed

2024-01-24 22:32 UTC, vasu31dev approved these changes

2024-01-24 22:32 UTC, merged